configuraciones/urls.py
from django.urls import path
from .blankpdf import crearConfigurador
from .views import (FuentesCreate, 
                    EmpresaUpdate,
                    ConfigImpresionRemitoCreate,
                    ConfigImpresionRemitoUpdate,
                    configuracionesIndex)



urlpatterns = [
    path('configuraciones/', configuracionesIndex, name='configuraciones'),
    path('configimpresionremito/crear/', ConfigImpresionRemitoCreate.as_view(), name='ConfigImpresionRemitoCreate'),
    path('remitopdf/blankpdf/', crearConfigurador, name='blankpdf'),
    ]

informes/urls.py
from django.urls import path
from .views import (main_informes,
                    pendiente_x_cronograma, 
                    obtener_productos)

urlpatterns = [
    path('', main_informes, name='main_informes'),
    path('cronograma/', pendiente_x_cronograma, name='pendiente_x_cronograma'),
    path('cronograma/<int:id_cronograma>/', obtener_productos, name='obtener_productos'),
    ]

inicio/urls.py
from .views import inicio, abm
from django.urls import path, include

urlpatterns = [
                path('', inicio, name='inicio'),
                path('abm/', abm, name='abm'),
]

upoc/urls.py
from django.urls import path
from .views import subir_oc

urlpatterns = [
    path('', subir_oc.as_view(), name='SubirOC'),
    ]

vd/urls.py
from django.contrib import admin
#from django.contrib.auth import urls
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include(('inicio.urls', 'inicio'), namespace='inicio')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('gral/', include(('gral.urls', 'gral'), namespace='gral')),
    path('venta/', include(('venta.urls', 'venta'), namespace='venta')),
    path('configuraciones/', include(('configuraciones.urls', 'configuraciones'), namespace='configuraciones')),
    path('upoc/', include(('upoc.urls', 'upoc'), namespace='upoc')),
    path('admin/', admin.site.urls, name='admin'),
    path('informes/', include(('informes.urls', 'informes'), namespace='informes')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

venta/urls.py
from django.urls import path, include


from venta.reportesPDF import remito, imprimir_etiqueta
from venta.ajax import (get_cronogramas, 
                        get_ordenesdecompra, 
                        get_productos, 
                        get_nextNumberRemito,
                        get_clientes,
                        cambiarValor,
                        conformarRemito,
                        get_pendientes_oc)
from    .views import (CronogramaCreate, 
                       CronogramaList,
                       CronogramaDetail,
                       CronogramaUpdate,  
                       OrdenCompraCompletoView,
                       OrdenCompraList,
                       OrdenCompraDetail,
                       RemitoCompletoView,
                       RemitoListView,
                       RemitoDetail,
                       PreImpresion,
                       RemitoConformador,
                       OrdenCompraUpdate,
                       RemitoUpdate)

urlpatterns = [
    #Cronograma
    path('cronograma/crear/', CronogramaCreate.as_view(), name='CronogramaCreate'),
    path('cronograma/listar/', CronogramaList.as_view(), name='CronogramaList'),
    path('cronograma/detalle/<int:pk>', CronogramaDetail.as_view(), name='CronogramaDetail'),
    path('cronograma/actualizar/<int:pk>', CronogramaUpdate.as_view(), name='CronogramaUpdate'),
    #Orden de compra
    path('ordencompra/listar/', OrdenCompraList.as_view(), name='OrdenCompraList'),
    path('ordencompra/detalle/<int:pk>', OrdenCompraDetail.as_view(), name='OrdenCompraDetail'),
    path('ordencompra/actualizar/<int:pk>', OrdenCompraUpdate.as_view(), name='OrdenCompraUpdate'),
    path('ordencompra/crear/', OrdenCompraCompletoView.as_view(), name='OrdenCompraCompleto'),
    path('preimpresion/<int:id_remito>', PreImpresion, name='Preimpresion'),
    #Impresion
    path('remitopdf/<int:id_remito>/<int:impresion>', remito, name='remitoPDF'),
    path('etiquetapdf/<int:id_remito>/', imprimir_etiqueta, name='etiquetasPDF'),
    #Remito
    path('remito/crear/', RemitoCompletoView.as_view(), name='RemitoCrear'),
    path('remito/listar/', RemitoListView.as_view(), name='RemitoListar'),
    path('remito/detail/<int:pk>', RemitoDetail.as_view(), name='RemitoDetail'),
    path('remito/actualizar/<int:pk>', RemitoUpdate.as_view(), name='RemitoUpdate'), 
    path('remito/conformador/<int:pk>', RemitoConformador.as_view(), name='RemitoConformador'),
    #Ajax    
    path('ajax/get_cronogramas', get_cronogramas, name='get_cronogramas'),
    path('ajax/get_productos', get_productos, name='get_productos'),
    path('ajax/get_datos', get_ordenesdecompra, name='get_datos'),
    path('ajax/get_numeracion', get_nextNumberRemito, name='get_numeracionRM'),
    path('ajax/get_clientes', get_clientes, name='get_clientes'),
    path('ajax/cambiarValor', cambiarValor, name='cambiarValor'),
    path('ajax/conformarRemito', conformarRemito, name='conformarRemito'),
    path('ajax/get_pendientes_oc', get_pendientes_oc, name='get_pendientes_oc'),
]

inicio/models.py
from django.db import models

# Create your models here.

inicio/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

@login_required
def inicio(request):
	return render(request, 'index.html', {})

@login_required
def abm(request):
	'''abm
	Aquí se define el contexto que se pasara a la pagina para que muestre los botones como correspondan.
	
	'''
	context = {'Producto' : {'Crear Producto' : {'descripcion' : 'Permite generar productos nuevos.',
												 'url' : reverse_lazy('gral:ProductoCreate'),
												 },
							 'Listar Productos' : {'descripcion' : 'Lista de todos los productos.',
												 'url' : reverse_lazy('gral:ProductoListView'),
												 },
							},
				'Cliente' : {'Crear Cliente' : {'descripcion' : 'Permite dar de alta clientes.',
												'url' : reverse_lazy('gral:ClienteCreate')},
							},
				'Condiciones de Pago' : {'Crear Tipo de Valores' : {'descripcion': 'Crear tipo de valores: Cheques, Efectivo, etc.',
											'url' : reverse_lazy('gral:ClienteCreate')},
										 'Crear Condiciones de Pago' : {'descripcion' : 'Creación de condiciones de pago.',
										    'url' : reverse_lazy('gral:ClienteCreate')},
							},
				}
	return render(request, 'inicio/abm.html', {'context' : context})

inicio/templates/base.html
<!doctype html>
<html lang="es">

<head>
    {% include "./utils/base_cabecera.html" %}
    {% include "./utils/base_pie.html" %}
</head>

<body>
<!-- app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header -->
    {% if user.is_authenticated %}
            <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
    
    {% else %}
        <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header closed-sidebar">
    
    {% endif %}
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>    <div class="app-header__content">
                <div class="app-header-left">
                                               {% if user.is_authenticated %}
                   
                    <ul class="header-menu nav">
                        <li class="nav-item">
				<a href="{% url 'informes:main_informes'%}" class="nav-link">
                                <i class="nav-link-icon fa fa-database"> </i>
                                Informes
                            </a>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="{% url 'configuraciones:configuraciones' %}" class="nav-link">
                                <i class="nav-link-icon fa fa-cog"></i>
                                Configuraciones
                            </a>
                        </li>
                    </ul>        
                 {% endif %}   
                 </div>
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        	
                                        	
    {% if user.is_authenticated %}
     <p>Usuario:  {{ user.get_username }}</p>
     <p><a href="{% url 'logout'%}?next={{request.path}}">Cerrar Sesión</a></p>   
   {% else %}
     <p><a href="{% url 'login'%}?next={{request.path}}">Ingresar</a></p>   
   {% endif %} 

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>        </div>
            </div>
        </div>       
               <div class="app-main">
                <div class="app-sidebar sidebar-shadow">
                    <div class="app-header__logo">
                        <div class="logo-src"></div>
                        <div class="header__pane ml-auto">
                            <div>
                            	<!-- hamburger close-sidebar-btn hamburger--elastic is-active -->
                            	  {% if user.is_authenticated %}
                            	<button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            	{% else %}
                                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic is-active" data-class="closed-sidebar">
                                {% endif %}
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="app-header__mobile-menu">
                        <div>
                            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                        </div>
                    </div>
                    <div class="app-header__menu">
                        <span>
                            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                                <span class="btn-icon-wrapper">
                                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                                </span>
                            </button>
                        </span>
                    </div>    <div class="scrollbar-sidebar">
                        <div class="app-sidebar__inner">
                            {% if user.is_authenticated %}
                        
                            <ul class="vertical-nav-menu">
                                <li class="app-sidebar__heading">Dashboards</li>
                                  <li>
                                     <a href="{% url 'inicio:abm' %}" class="mm-active">
                                        <i class="metismenu-icon pe-7s-rocket"></i>
                                        ABM
                                    </a>
                                </li>
                               <!-- <li class="app-sidebar__heading">UI Components</li> -->
                                <li>
                                    <a href="#">
                                        <i class="metismenu-icon pe-7s-monitor"></i>
                                        Circuito de Venta
                                        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                                    </a>
                                    <ul>
                                    	<li><i class="pe-7s-settings">  Cronograma</i></li>
                                        <li>
                                            <a href="{% url 'venta:CronogramaCreate' %}">
                                                <i class="metismenu-icon"></i>
                                                Crear Cronograma
                                            </a>
                                        </li>
                                         <li>
                                            <a href="{% url 'venta:CronogramaList' %}">
                                                <i class="metismenu-icon"></i>
                                                Listar Cronogramas
                                            </a>
                                        </li>
                                    	<li><i class="pe-7s-settings">  Orden de Compra</i></li>
                                         <li>
                                            <a href="{% url 'venta:OrdenCompraCompleto' %}">
                                                <i class="metismenu-icon"></i>
                                                Crear Orden de Compra
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'venta:OrdenCompraList' %}">
                                                <i class="metismenu-icon"></i>
                                                Listar Orden de Compra
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'upoc:SubirOC' %}">
                                                <i class="metismenu-icon"></i>
                                                Subir O.C
                                            </a>
                                        </li>
                                    	<li><i class="pe-7s-settings">  Remito</i></li>
                                          <li>
                                            <a href="{% url 'venta:RemitoCrear' %}">
                                                <i class="metismenu-icon"></i>
                                                Crear Remitos
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'venta:RemitoListar' %}">
                                                <i class="metismenu-icon"></i>
                                                Listar Remitos
                                            </a>
                                        </li>
                                        <li><i class="pe-7s-settings">Facturación</i></li>
                                                                           <li>
                                            <a href="{% url 'venta:RemitoCrear' %}">
                                                <i class="metismenu-icon"></i>
                                                Facturar
                                            </a>
                                        </li>
                                    </ul>
                                    


                                                                    <li>
                                    <a href="#">
                                        <i class="metismenu-icon pe-7s-wallet"></i>
                                        Administracion
                                        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                                    </a>
                                    <ul>
                                        <li>
                                            <a href="{% url 'admin:index' %}">
                                                <i class="metismenu-icon"></i>
                                                Administracion
                                            </a>
                                        </li>
                                        </ul>
                                </li>
                            </ul>

                            {% endif %}
                        </div>
                    </div>
                </div>    <div class="app-main__outer">
                <div class="app-main__inner">
                                            {% if user.is_authenticated %}
                
			{% block cuerpo %}
			
			
			{% endblock %}
			{% else %}
			{% block sesion%}
			
			{% endblock %}
			{% endif %}
			</div>
    </div>
        </div>
    </div>
    {% block footer %}
    {% endblock footer %}
</body>

</html>

inicio/templates/index.html
{% extends 'base.html' %}