gral/urls.py
from django.urls import path
from gral.views import (ProductoCreate, 
                        ClienteCreate, 
                        ProductoListView, 
                        ProductoDetailView,
                        ClienteListView,
                        ClienteDetailView,
                        ProductoCreatePartial,
                        ProductoCreateBS,
                        )

urlpatterns = [
    path('producto/crear/', ProductoCreate.as_view(), name='ProductoCreate'),
    path('producto/bs/crear', ProductoCreateBS.as_view(), name='ProductoCreatePartial'),
    path('producto/listar/', ProductoListView.as_view(), name='ProductoListView'),
    path('cliente/crear/', ClienteCreate.as_view(), name='ClienteCreate'),
    path('cliente/listar/', ClienteListView.as_view(), name='ClienteListView'),
    path('cliente/detalle/<int:pk>', ClienteDetailView.as_view(), name='ClienteDetail'),
    path('producto/detalle/<int:pk>', ProductoDetailView.as_view(), name='ProductoDetail'),
]

inicio/urls.py
from .views import inicio, abm
from django.urls import path, include

urlpatterns = [
                path('', inicio, name='inicio'),
                path('abm/', abm, name='abm'),
]

vd/urls.py
from django.contrib import admin
#from django.contrib.auth import urls
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include(('inicio.urls', 'inicio'), namespace='inicio')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('gral/', include(('gral.urls', 'gral'), namespace='gral')),
    path('venta/', include(('venta.urls', 'venta'), namespace='venta')),
    path('configuraciones/', include(('configuraciones.urls', 'configuraciones'), namespace='configuraciones')),
    path('upoc/', include(('upoc.urls', 'upoc'), namespace='upoc')),
    path('admin/', admin.site.urls, name='admin'),
    path('informes/', include(('informes.urls', 'informes'), namespace='informes')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

venta/urls.py
from django.urls import path, include


from venta.reportesPDF import remito, imprimir_etiqueta
from venta.ajax import (get_cronogramas, 
                        get_ordenesdecompra, 
                        get_productos, 
                        get_nextNumberRemito,
                        get_clientes,
                        cambiarValor,
                        conformarRemito,
                        get_pendientes_oc)
from    .views import (CronogramaCreate, 
                       CronogramaList,
                       CronogramaDetail,
                       CronogramaUpdate,  
                       OrdenCompraCompletoView,
                       OrdenCompraList,
                       OrdenCompraDetail,
                       RemitoCompletoView,
                       RemitoListView,
                       RemitoDetail,
                       PreImpresion,
                       RemitoConformador,
                       OrdenCompraUpdate,
                       RemitoUpdate)

urlpatterns = [
    #Cronograma
    path('cronograma/crear/', CronogramaCreate.as_view(), name='CronogramaCreate'),
    path('cronograma/listar/', CronogramaList.as_view(), name='CronogramaList'),
    path('cronograma/detalle/<int:pk>', CronogramaDetail.as_view(), name='CronogramaDetail'),
    path('cronograma/actualizar/<int:pk>', CronogramaUpdate.as_view(), name='CronogramaUpdate'),
    #Orden de compra
    path('ordencompra/listar/', OrdenCompraList.as_view(), name='OrdenCompraList'),
    path('ordencompra/detalle/<int:pk>', OrdenCompraDetail.as_view(), name='OrdenCompraDetail'),
    path('ordencompra/actualizar/<int:pk>', OrdenCompraUpdate.as_view(), name='OrdenCompraUpdate'),
    path('ordencompra/crear/', OrdenCompraCompletoView.as_view(), name='OrdenCompraCompleto'),
    path('preimpresion/<int:id_remito>', PreImpresion, name='Preimpresion'),
    #Impresion
    path('remitopdf/<int:id_remito>/<int:impresion>', remito, name='remitoPDF'),
    path('etiquetapdf/<int:id_remito>/', imprimir_etiqueta, name='etiquetasPDF'),
    #Remito
    path('remito/crear/', RemitoCompletoView.as_view(), name='RemitoCrear'),
    path('remito/listar/', RemitoListView.as_view(), name='RemitoListar'),
    path('remito/detail/<int:pk>', RemitoDetail.as_view(), name='RemitoDetail'),
    path('remito/actualizar/<int:pk>', RemitoUpdate.as_view(), name='RemitoUpdate'), 
    path('remito/conformador/<int:pk>', RemitoConformador.as_view(), name='RemitoConformador'),
    #Ajax    
    path('ajax/get_cronogramas', get_cronogramas, name='get_cronogramas'),
    path('ajax/get_productos', get_productos, name='get_productos'),
    path('ajax/get_datos', get_ordenesdecompra, name='get_datos'),
    path('ajax/get_numeracion', get_nextNumberRemito, name='get_numeracionRM'),
    path('ajax/get_clientes', get_clientes, name='get_clientes'),
    path('ajax/cambiarValor', cambiarValor, name='cambiarValor'),
    path('ajax/conformarRemito', conformarRemito, name='conformarRemito'),
    path('ajax/get_pendientes_oc', get_pendientes_oc, name='get_pendientes_oc'),
]

inicio/models.py
from django.db import models

# Create your models here.

inicio/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

@login_required
def inicio(request):
	return render(request, 'index.html', {})

@login_required
def abm(request):
	'''abm
	Aquí se define el contexto que se pasara a la pagina para que muestre los botones como correspondan.
	
	'''
	context = {'Producto' : {'Crear Producto' : {'descripcion' : 'Permite generar productos nuevos.',
												 'url' : reverse_lazy('gral:ProductoCreate'),
												 },
							 'Listar Productos' : {'descripcion' : 'Lista de todos los productos.',
												 'url' : reverse_lazy('gral:ProductoListView'),
												 },
							},
				'Cliente' : {'Crear Cliente' : {'descripcion' : 'Permite dar de alta clientes.',
												'url' : reverse_lazy('gral:ClienteCreate')},
							},
				'Condiciones de Pago' : {'Crear Tipo de Valores' : {'descripcion': 'Crear tipo de valores: Cheques, Efectivo, etc.',
											'url' : reverse_lazy('gral:ClienteCreate')},
										 'Crear Condiciones de Pago' : {'descripcion' : 'Creación de condiciones de pago.',
										    'url' : reverse_lazy('gral:ClienteCreate')},
							},
				}
	return render(request, 'inicio/abm.html', {'context' : context})

venta/views.py
#imports Django
from django.shortcuts import render, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, FormView, DetailView, UpdateView
from django.db import DatabaseError, transaction
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


#Imports de la aplicación.
from .models import (Cronograma, 
					 OrdenCompra, 
					 ProductoLineasOC, 
					 Remito, 
					 ProductoLineasRM)
from .forms  import (CronogramaCreateForm,
					 CronogramaUpdateForm,
					 OrdenCompraCabecera,
					 ProductoLineasOCForm,
					 ProductoLineasOCFormSet,
					 ProductoLineasRMForm,
					 ProductoLineasRMFormSet,
					 RemitoCabecera,
					 ModelProductoLineasOCFormSet,
                                         ModelProductoLineasRMFormSet)
					 
from configuraciones.models import ConfigImpresionRemito
##
#
# CRONOGRAMA
#
##

class CronogramaCreate(LoginRequiredMixin, CreateView):
	template_name = 'venta/cronograma_form.html'
	form_class = CronogramaCreateForm
	success_url = reverse_lazy('venta:CronogramaList')



class CronogramaList(LoginRequiredMixin, ListView):
	model = Cronograma


class CronogramaDetail(LoginRequiredMixin, DetailView):
	model = Cronograma
	
class CronogramaUpdate(LoginRequiredMixin, UpdateView):
	model= Cronograma
	template_name = 'venta/cronograma_form.html'
	form_class = CronogramaUpdateForm
	success_url = reverse_lazy('venta:CronogramaList')

##
#
# ORDEN DE COMPRA
#
##
###################### DETAIL
class OrdenCompraDetail(LoginRequiredMixin, DetailView):
	model = OrdenCompra
	#form_class = OrdenCompraCabecera
	template_name = 'venta/ordencompra_detail.html'

	
	def get_context_data(self, **kwargs):
		instance = super(OrdenCompraDetail, self).get_context_data(**kwargs)
		lineasOC = ProductoLineasOC.objects.filter(OrdenCompra=instance['object'].pk)
		instance['ordendecompramain'] = lineasOC
		valor_total = 0
		for sum in instance['ordendecompramain']:
			valor_total += sum.total
		instance['total_orden'] = valor_total
		return instance


###################### LIST

class OrdenCompraList(LoginRequiredMixin, ListView):
	model = OrdenCompra


###################### VIEW

class lineaProductoOCList(LoginRequiredMixin, ListView):
	model = OrdenCompra


###################### CREATE



class OrdenCompraCompletoView(LoginRequiredMixin, CreateView):
    form_class = OrdenCompraCabecera
    #model = OrdenCompra
    success_url = reverse_lazy('venta:OrdenCompraList')
    template_name = 'venta/ordencompra_form.html'
    
    def get_context_data(self, **kwargs):
        data = super(OrdenCompraCompletoView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['ordendecompramain'] = ProductoLineasOCFormSet(self.request.POST)
        else:
            data['ordendecompramain'] = ProductoLineasOCFormSet()
        return data
    def form_valid(self, form):
        context = self.get_context_data()
        ordendecompramain = context['ordendecompramain']
        with transaction.atomic():
            self.object = form.save()
            if ordendecompramain.is_valid():
            	ordendecompramain.instance = self.object
            	ordendecompramain.save()
        return super(OrdenCompraCompletoView, self).form_valid(form)


###################### UPDATE


class OrdenCompraUpdate(LoginRequiredMixin, UpdateView):
	model = OrdenCompra
	form_class = OrdenCompraCabecera
	formset_class = ProductoLineasOCFormSet
	template_name = 'venta/ordencompra_form.html'
	success_url = reverse_lazy('venta:OrdenCompraList')
	def get_context_data(self, *args, **kwargs):
		context = super(OrdenCompraUpdate, self).get_context_data(**kwargs)
		qs = ProductoLineasOC.objects.filter(OrdenCompra = self.get_object())
		formset = ModelProductoLineasOCFormSet(queryset=qs)
		context['ordendecompramain'] = formset
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		qs = ProductoLineasOC.objects.filter(OrdenCompra=self.get_object())
		formsets = ModelProductoLineasOCFormSet(self.request.POST, queryset=qs)#, queryset=qs)
		resultado = formsets[-1:][0]
		if form.is_valid():
			for fs in formsets:
				if fs.is_valid():
					fs.save()
			return self.form_valid(form)
		return self.form_invalid(form)

#class OrdenCompraCreate(CreateView):
    #model = OrdenCompra
#    form_class = OrdenCompraCabecera

# FIN ORDEN DE COMPRA #

##
#
# REMITO
#	
##

################### DETAIL

class RemitoDetail(LoginRequiredMixin, DetailView):
	model = Remito #Importamos el modelo
	template_name = 'venta/remito_detail.html'
	def get_context_data(self, **kwargs):
		instance = super(RemitoDetail, self).get_context_data(**kwargs)
		lineasRM = ProductoLineasRM.objects.filter(remito=instance['object'].pk)
		instance['remito_linea'] = lineasRM
		return instance

#class RemitoUpdate(LoginRequiredMixin, UpdateView):
#	form_class = RemitoCabecera
#	template_name = 'venta/remito_form.html'
	


class RemitoConformador(LoginRequiredMixin, UpdateView):
	model = Remito #Importamos el modelo
	fields = '__all__'
	template_name = 'venta/conformador_detail.html'
	def get_context_data(self, **kwargs):
		instance = super(RemitoConformador, self).get_context_data(**kwargs)
		lineasRM = ProductoLineasRM.objects.filter(remito=instance['object'].pk)
		instance['remito_linea'] = lineasRM
		return instance



################### LIST

class RemitoListView(LoginRequiredMixin, ListView):
	model = Remito


###################### VIEW

class lineaProductoRMList(LoginRequiredMixin, ListView):
	model = RemitoCabecera

##################### CREATE

class RemitoCompletoView(LoginRequiredMixin, CreateView):
	form_class = RemitoCabecera #Utilizamos el form_class
	template_name = 'venta/remito_form.html' #definimos el template_name
	#Con el get_context_data vamos a pasar el formulario y controlar.
	def get_context_data(self, **kwargs):
		data = super(RemitoCompletoView, self).get_context_data(**kwargs) #Utilizamos el super para 
																		  #llamar a la función
		if self.request.POST:
			data['remitomain'] = ProductoLineasRMFormSet(self.request.POST)
		else:
			data['remitomain'] = ProductoLineasRMFormSet()
		return data
       
	def form_valid(self, form):
		context = self.get_context_data()
		remitomain = context['remitomain']
		with transaction.atomic():
			self.object = form.save()
			if remitomain.is_valid():
				remitomain.instance = self.object
				remitomain.save()
		return super(RemitoCompletoView, self).form_valid(form)
	
	def get_success_url(self):
		return reverse_lazy('venta:Preimpresion', kwargs={'id_remito': self.object.pk})

class RemitoUpdate(LoginRequiredMixin, UpdateView):
    model = Remito
    form_class = RemitoCabecera
    formset_class = ProductoLineasRMFormSet
    template_name = 'venta/remito_form.html'
    success_url = reverse_lazy('venta:RemitoListar')
    def get_context_data(self, *args, **kwargs):
            context = super(RemitoUpdate, self).get_context_data(**kwargs)
            qs = ProductoLineasRM.objects.filter(remito=self.get_object())
            formset = ModelProductoLineasRMFormSet(queryset=qs)
            context['remitomain'] = formset
            return context
    
    def post(self, request, *args, **kwargs):
            self.object = self.get_object()
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            qs = ProductoLineasRM.objects.filter(remito=self.get_object())
            formsets = ModelProductoLineasRMFormSet(self.request.POST, queryset=qs)#, queryset=qs)
            resultado = formsets[-1:][0]
            if form.is_valid():
                for fs in formsets:
                    if fs.is_valid():
                        fs.save()
                    return self.form_valid(form)
            return self.form_invalid(form)


#class RemitoCreate(CreateView):
#	form_class = RemitoCabecera
######################### PAGINA PRE-IMPRESIÓN.

def PreImpresion(request, id_remito):
	model = Remito.objects.filter(pk=id_remito).last()
	impresoras = ConfigImpresionRemito.objects.all()
	return render(request, 'venta/preimpresion.html', {'remito' : model, 'impresoras' : impresoras}) 
	

inicio/templates/venta/cronograma_form.html
{% extends '../base.html' %}

{%  block cuerpo %}

<div class="app-page-title">
<div class="page-title-heading">
   <div class="page-title-icon">
         <i class="pe-7s-magic-wand icon-gradient bg-mixed-hopes"></i>
    </div>
		<div>{% if form.nombre.value|length > 0  %} 
					Actualizar
			 {% else %}
			 		Crear
			 {% endif%}
			  Conograma
			 </div>
                                     
</div>
</div>
   
<div class="main-card mb-3 card">
   <div class="card-body">
   <h5 class="card-title">Formulario Alta de Cronograma</h5>

<form method="post">{% csrf_token %}
<p>
    {{ form.nombre.label_tag }}
    {{ form.nombre }}
</p>
	{% for error in form.non_field_errors %}
	 	<p class='help text-danger'>{{ error }}</p>
	{% endfor %}
<p>   
    {{ form.cliente.label_tag }}
    {{ form.cliente }}
</p>
<p>
    {{ form.fecha_inicio.label_tag }}
    {{ form.fecha_inicio }}
</p>
<p>
    {{ form.fecha_finalizacion.label_tag }}
    {{ form.fecha_finalizacion }}
</p>

	{% if form.nombre.value|length > 0  %} 
	<p>
	{{ form.terminada.label_tag }}
	{{ form.terminada }}
	</p>
	{% endif %}

    <button type="submit" class="btn btn-primary">
			{% if form.nombre.value|length > 0  %} 
					Actualizar
			 {% else %}
			 		Guardar
			 {% endif%}
	</button>
</form>
</div>
</div>
{% include './js/cronograma_form.js'%}
{% endblock %}

inicio/templates/venta/cronograma_list.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="app-page-title">
	<div class="page-title-heading">
		<div class="page-title-icon">
			<i class="pe-7s-menu icon-gradient bg-ripe-malin"> </i>
		</div>
		<div>Listado de Cronograma</div>
	</div>
	
	<!-- Inicio Filtros -->
	<hr/>
	<div class="main-card mb-2 card">
		<div class="card-body">
			<h5 class="card-title">Filtros</h5>
			<table class="table table-hover table-fixed">
				<tr>
					<td>
						<label for="filtroNombre">Nombre de Campaña:</label>
						<input type="text" class="form-control" id="filtroNombre"
							onkeyup="filtroNombreCliente()"
							placeholder="Ingrese una Campaña..." /></td>
					<td>
						<label for="clientes_select">Cliente:</label>
						<select id="clientes_select" class="form-control"
							onchange="filtroNombreCliente()">
					</td>
					<td>
						<label for="filtroEstado">Estados</label>
						<select class="form-control" id="filtroEstado"
							onchange="filtroNombreCliente()">
							<option value="*">Todos</option>
							<option value="False">Activas</option>
							<option value="True">Terminadas</option>
						</select>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<!-- Fin Filtros 	-->
</div>


{% if object_list %}
<div class="main-card mb-3 card">
	<div class="card-body">
	<h5 class="card-title">Listado de cronogramas.</h5>
		<table class="table table-hover table-fixed" id="tablaResultado">
		  <tr>
		    <th>Nombre</th>
		    <th>Fecha Inicio</th>
		    <th>Fecha Finalización</th>
		    <th>Cliente</th>
		    <th>Terminada</th>
		  </tr>   
		      {% for cronograma in object_list %}
		   <tr>
		      <td> <a href="{% url 'venta:CronogramaDetail' pk=cronograma.id %}">
		      	<i class="pe-7s-box2 icon-gradient bg-amy-crisp">
		        </i>
		        {{cronograma}}
		    </a>
		      </td>
		      <td>
		        {{cronograma.fecha_inicio }}
		      </td>
		      <td>
		        {{cronograma.fecha_finalizacion }}
		      </td>
		      <td>
		        {{cronograma.cliente}}
		      </td>
		      <td>
		        {{ cronograma.terminada }}
		      </td>
		    </tr>
		      {% endfor %}
		
		    {% else %}
		      <p>No hay registros para mostrar.</p>
		    {% endif %}      
		</table>
	</div>
</div>
<a href="{% url 'inicio:abm' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-wallet icon-gradient bg-plum-plate"></i>Ir al ABM
</button>
</a>	
<a href="{% url 'venta:CronogramaCreate' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-magic-wand icon-gradient bg-mixed-hopes"></i>Crear Cronograma
</button> 
</a>


{% include "./js/cronograma_list.js" %}
{% endblock %}


inicio/templates/venta/ordencompra_detail.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="main-card mb-3 card">
	<div class="card-body">
		<h5 class="card-title">Detalle de Orden de compra: {{ ordencompra }}</h5>
		<table class="table table-hover table-fixed">
		<tr>
			<th>
				Campo
			</th>
			<th>
				Detalle
			</th>
		</tr>
			<tr>
				<td>Orden de compra: </td>
				<td><i class="pe-7s-box2 icon-gradient bg-amy-crisp">
		        </i>
		        	{{ ordencompra }}
		      </td>
		      </tr>
		      <tr>
		      <td>Fecha de Emisión: </td>
		      
		      <td>
		        {{ ordencompra.fecha_emision }}
		      </td>
		      </tr>
		      
		      <tr>
		      <td>Cliente: </td>
		      <td>
		        {{ ordencompra.cliente }}
		        </td>
		      </tr>	
		</table>
	</div>
		<div class="card-body">
	<h5 class="card-title">Detalle Orden de compra</h5>
	
		<table class="table table-hover table-fixed">
		<tr>
		<th>Producto (Código)</th>
		<th>Cantidad</th>
		<th>Precio</th>
		<th>Total</th>
		</tr>
		{% for lista in ordendecompramain %}
		<tr>
			<td><a href="{% url 'gral:ProductoDetail' lista.producto.pk%}">{{ lista.producto.nombre_completo }}</a></td>
			<td>{{ lista.cantidad}} </td>
			<td>$ {{ lista.precio_unitario}}</td>
			<td>$ {{ lista.total }}</td>
			
		</tr>
			{% endfor %}
			<tr>
			<td></td>
			<td><h3>Total:</h3></td>
			<td></td>
			<td><h5>$ {{ total_orden }}</h5>
			</td>
			</tr>
        </table>
	<a href="{% url 'venta:OrdenCompraUpdate' pk=ordencompra.id %}"><button class="btn btn-primary">Actualizar</button></a>
    </div>
</div>
<a href="{% url 'venta:OrdenCompraList' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-angle-left-circle">Volver</i>
</button>
	</a>		 
{% endblock %}

inicio/templates/venta/preimpresion.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="main-card mb-3 card">
	<div class="card-body">
		<h5 class="card-title">Detalle de {{ remito }}</h5>
		<table class="table table-hover table-fixed">
		<tr>
			<th>
				Campo
			</th>
			<th>
				Detalle
			</th>
		</tr>
		<tr>
				<td>Referencia Externa: </td>
				<td><i class="pe-7s-box2 icon-gradient bg-amy-crisp">
		        </i>
		        	{{ remito }}
		      </td>
		      </tr>
			<tr>
		      <td>Orden de Compra: </td>
		      
		      <td>
		        {{ remito.ordencompra }}
		      </td>
		      </tr>
			
		      <tr>
		      <td>Fecha de Emisión: </td>
		      
		      <td>
		        {{ remito.fecha_emision }}
		      </td>
		      </tr>
		      
		      <tr>
		      <td>Cliente: </td>
		      <td>
		        {{ remito.cliente }}
		        </td>
		      </tr>
		      <tr>
		      <td>Formato Impresion: </td>
		      <td>
		        {{ remito.formato_de_impresion }}
		        </td>
		      </tr>
		      
		      <tr>
		      <td>Imprimir Etiquetas: </td>
		      <td>
		        <input type="checkbox" name="imprimir_etiquetas" checked>
		        </td>
		      </tr>
		      <tr>
		      <td>
		      	
		      	<a href="{% url 'venta:remitoPDF' id_remito=remito.pk impresion=1 %}" ><input type="button" class="btn btn-primary" value="Imprimir"></a>
				  <a href="{% url 'venta:etiquetasPDF' id_remito=remito.pk %}" ><input type="button" class="btn btn-primary" value="Imprimir Etiquetas"></a>
			  	<a href="#"><input type="button" class="btn btn-primary" value="Modificar Remito"></a>
				<a href="{% url 'venta:RemitoDetail' pk=remito.pk %}"><input type="button" class="btn btn-primary" value="Ver Detalles"></a>
				
			<td>
				</tr>
		</table>
		
		<select name="impresora"{% for impresora in impresoras %}
								><option value="{{ impresora.pk }}">{{ impresora }}</option>
								{% endfor %}
								
		</select>
		
		
	</div>
</div>
<a href="{% url 'venta:RemitoListar' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-angle-left-circle">Volver</i>
</button>
	</a>		 


{% endblock %}

inicio/templates/venta/remito_list.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="app-page-title">
<div class="page-title-heading">
   <div class="page-title-icon">
                                        <i class="pe-7s-menu icon-gradient bg-ripe-malin">
                                        </i>
                                    </div>
<div>Listado de Remitos Generados</div>
                                     
                                    </div>
</div>
<hr/>
	<div class="main-card mb-2 card">
		<div class="card-body">
			<h5 class="card-title">Filtros</h5>
			<table class="table table-hover table-fixed">
				<tr>
					<td>
						<label for="filtroNombre">Referencia Remito:</label>
						<input type="text" class="form-control" id="filtroNombre"
							onkeyup="filtroNombreCliente()"
							placeholder="Ingrese referencia de Remito..." /></td>
					<td>
						<label for="clientes_select">Cliente:</label>
						<select id="clientes_select" class="form-control"
							onchange="filtroNombreCliente()">
					</td>
					<td>
						<label for="filtroEstado">Estados</label>
						<select class="form-control" id="filtroEstado"
							onchange="filtroNombreCliente()">
							<option value="*">Todos</option>
							<option value="False">SIN</option>
							<option value="True">CONFORMADO</option>
						</select>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>

    {% if object_list %}
<div class="main-card mb-3 card">
	<div class="card-body">
	<h5 class="card-title">Listado de Remitos.</h5>
		<table class="table table-hover table-fixed" id="tablaResultado">
		  <tr>
		    <th>Referencia</th>
		    <th>Tipo de Documento</th>
		    <th>Fecha Emision</th>
		    <th>Cliente</th>
			<th>Conformado</th>
		    <th>Ver Detalle</th>
		  </tr>   
		      {% for remito in object_list %}
		   <tr>
		      <td>
			  <a href="{% url 'venta:RemitoDetail' pk=remito.id %}">
			  <i class="pe-7s-box2 icon-gradient bg-amy-crisp">
		        </i>
		        {{remito}}
		      </td>
			  </a>
		      <td>
		      	{{remito.tipo_documento}}
		      </td>
		      <td>
		        {{remito.fecha_emision }}
		      </td>
		      <td>
		        {{remito.cliente}}
		      </td>
			  <td>
		        {{remito.conformado}}
		      </td>
		      <td>
			      <a href="{% url 'venta:RemitoConformador' pk=remito.id %}">
			      	<i class="pe-7s-angle-up-circle">
			      			Conformar
			      	</i>
			      </a>
		      </td>
		    </tr>
		      {% endfor %}
		
		    {% else %}
		      <p>No hay registros para mostrar.</p>
		    {% endif %}      
		</table>
		
	</div>
</div>
<a href="{% url 'inicio:abm' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-wallet icon-gradient bg-plum-plate"></i>Ir al ABM
</button>
</a>	
<a href="{% url 'venta:RemitoCrear' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-magic-wand icon-gradient bg-mixed-hopes"></i>Crear Remito
</button>
</a>
{% include './js/remito_list.js' %}
{% endblock %}