gral/urls.py
from django.urls import path
from gral.views import (ProductoCreate, 
                        ClienteCreate, 
                        ProductoListView, 
                        ProductoDetailView,
                        ClienteListView,
                        ClienteDetailView,
                        ProductoCreatePartial,
                        ProductoCreateBS,
                        )

urlpatterns = [
    path('producto/crear/', ProductoCreate.as_view(), name='ProductoCreate'),
    path('producto/bs/crear', ProductoCreateBS.as_view(), name='ProductoCreatePartial'),
    path('producto/listar/', ProductoListView.as_view(), name='ProductoListView'),
    path('cliente/crear/', ClienteCreate.as_view(), name='ClienteCreate'),
    path('cliente/listar/', ClienteListView.as_view(), name='ClienteListView'),
    path('cliente/detalle/<int:pk>', ClienteDetailView.as_view(), name='ClienteDetail'),
    path('producto/detalle/<int:pk>', ProductoDetailView.as_view(), name='ProductoDetail'),
]

inicio/urls.py
from .views import inicio, abm
from django.urls import path, include

urlpatterns = [
                path('', inicio, name='inicio'),
                path('abm/', abm, name='abm'),
]

vd/urls.py
from django.contrib import admin
#from django.contrib.auth import urls
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include(('inicio.urls', 'inicio'), namespace='inicio')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('gral/', include(('gral.urls', 'gral'), namespace='gral')),
    path('venta/', include(('venta.urls', 'venta'), namespace='venta')),
    path('configuraciones/', include(('configuraciones.urls', 'configuraciones'), namespace='configuraciones')),
    path('upoc/', include(('upoc.urls', 'upoc'), namespace='upoc')),
    path('admin/', admin.site.urls, name='admin'),
    path('informes/', include(('informes.urls', 'informes'), namespace='informes')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inicio/models.py
from django.db import models

# Create your models here.

gral/forms.py
from django import forms
from bootstrap_modal_forms.forms import BSModalForm
from .models import (   Peso, 
                        Medicion, 
                        Cuerpos, 
                        FamiliaInsumos, 
                        LineaInsumos, 
                        Insumos,
                        Cliente,
                        Producto)
 
""" 
class PesoCreateForm(forms.ModelForm):
    class Meta:
        model = Peso

 
class PesoListForm(forms.ModelForm):
    class Meta:
        model = Peso
 
class MedicionCreateForm(forms.ModelForm):
    class Meta:
        model = Medicion

 
class MedicionListForm(forms.ModelForm):
    class Meta:
        model = Medicion
 
class CuerposCreateForm(forms.ModelForm):
    class Meta:
        model = Cuerpos

 
class CuerposListForm(forms.ModelForm):
    class Meta:
        model = Cuerpos
 
class FamiliaInsumosCreateForms(forms.ModelForm):
    class Meta:
        model = FamiliaInsumos
 
class FamiliaInsumosListForms(forms.ModelForm):
    class Meta:
        model = FamiliaInsumos
 
class LineaInsumosCreateForms(forms.ModelForm):
    class Meta:
        model = LineaInsumos
 
class LineaInsumosListForms(forms.ModelForm):
    class Meta:
        model = LineaInsumos
 
class InsumoCreateForm(forms.ModelForm):
    class Meta:
        model = Insumo
 
class InsumoListForm(forms.ModelForm):
    class Meta:
        model = Insumo

"""
################### FIN INSUMOS



class ClienteCreateForm(forms.ModelForm):
    class Meta:
            model = Cliente
            fields = ('__all__')
            class_control = {'class' : 'form-control'}
            widgets =   {
                        'razon_social'      :   forms.TextInput(attrs=class_control),
                        'nombre_corto'      :   forms.TextInput(attrs=class_control),
                        'cuit'              :   forms.TextInput(attrs=class_control),
                        'direccion_fiscal'  :   forms.TextInput(attrs=class_control),
                        'direccion_entrega' :   forms.TextInput(attrs=class_control),
                        'condicion_iva'     :   forms.TextInput(attrs=class_control),
                        'observaciones'     :   forms.Textarea(attrs=class_control),
                        }
            



class ProductoCreateForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('codigo', 'cliente', 'descripcion',)
        widgets = {
            'codigo' : forms.TextInput(attrs={'class' : 'form-control'}),
            'cliente' : forms.Select(attrs={'class' : 'form-control'}),
            'descripcion' : forms.TextInput(attrs={'class' : 'form-control'}),

            }


class ProductoCreateBS(BSModalForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'cliente', 'descripcion']
        widgets = {
            'codigo' : forms.TextInput(attrs={'class' : 'form-control'}),
            'cliente' : forms.Select(attrs={'class' : 'form-control'}),
            'descripcion' : forms.TextInput(attrs={'class' : 'form-control'}),
            }

gral/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from bootstrap_modal_forms.generic import BSModalCreateView

from .forms import (ProductoCreateForm, ClienteCreateForm, ProductoCreateBS)
from .models import (Producto, Cliente)


"""Vistas Cliente
"""

class ClienteCreate(LoginRequiredMixin, CreateView):
	form_class = ClienteCreateForm
	template_name = 'gral/cliente_form.html'
	success_url = reverse_lazy('gral:ClienteListView')

class ClienteListView(LoginRequiredMixin, ListView):
	model 			= Cliente
	template_name 	= 'gral/cliente_list.html'


class ClienteDetailView(LoginRequiredMixin, DetailView):
	model = Cliente

##################### FIN CLIENTE

"""Vistas Productos.
"""

class ProductoCreate(LoginRequiredMixin, CreateView):
	form_class = ProductoCreateForm
	template_name = 'gral/producto_form.html'
	success_url = reverse_lazy('gral:ProductoListView')

class ProductoCreatePartial(LoginRequiredMixin, CreateView):
	form_class = ProductoCreateForm
	template_name = 'gral/partials/pProducto_form.html'
	success_url = None



class ProductoListView(LoginRequiredMixin, ListView):
	model = Producto
	#template_name = 'gral/partials/pProducto_list.html'
	template_name = 'gral/partials/producto_list.html'
	context_object_name = 'producto'


class ProductoDetailView(LoginRequiredMixin, DetailView):
	model = Producto
################### FIN PRODUCTO


class ProductoCreateBS(BSModalCreateView):
	template_name = 'gral/partials/pProducto_form.html'
	form_class = ProductoCreateBS
	success_message = 'Producto Creado.'
	success_url = reverse_lazy('venta:OrdenCompraCompleto')

inicio/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

@login_required
def inicio(request):
	return render(request, 'index.html', {})

@login_required
def abm(request):
	'''abm
	Aquí se define el contexto que se pasara a la pagina para que muestre los botones como correspondan.
	
	'''
	context = {'Producto' : {'Crear Producto' : {'descripcion' : 'Permite generar productos nuevos.',
												 'url' : reverse_lazy('gral:ProductoCreate'),
												 },
							 'Listar Productos' : {'descripcion' : 'Lista de todos los productos.',
												 'url' : reverse_lazy('gral:ProductoListView'),
												 },
							},
				'Cliente' : {'Crear Cliente' : {'descripcion' : 'Permite dar de alta clientes.',
												'url' : reverse_lazy('gral:ClienteCreate')},
							},
				'Condiciones de Pago' : {'Crear Tipo de Valores' : {'descripcion': 'Crear tipo de valores: Cheques, Efectivo, etc.',
											'url' : reverse_lazy('gral:ClienteCreate')},
										 'Crear Condiciones de Pago' : {'descripcion' : 'Creación de condiciones de pago.',
										    'url' : reverse_lazy('gral:ClienteCreate')},
							},
				}
	return render(request, 'inicio/abm.html', {'context' : context})

inicio/templates/gral/cliente_detail.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="main-card mb-3 card">
	<div class="card-body">
		<h5 class="card-title">Detalle del Cliente: {{ cliente.descripcion }}</h5>
		<table class="table table-hover table-fixed">
		<tr>
			<th>
				Campo
			</th>
			<th>
				Detalle
			</th>
		</tr>
			<tr>
				<td>Código: </td>
				<td><i class="pe-7s-box2 icon-gradient bg-amy-crisp">
		        </i>
		        	{{cliente.razon_social}}
		      </td>
		      </tr>
		      <tr>
		      <td>Descripción: </td>
		      
		      <td>
		        {{cliente.nombre_corto }}
		      </td>
		      </tr>
		      
		      <tr>
		      <td>Cliente: </td>
		      <td>
		       	
		       
		        {{cliente.cuit}}
		        </td>
		      </tr>	
		</table>
	</div>
</div>
<a href="{% url 'gral:ClienteListView' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-angle-left-circle">Volver</i>
</button>
	</a>		 


{% endblock %}

inicio/templates/gral/cliente_form.html
{% extends '../base.html' %} 
{% block cuerpo %}
<div class="app-page-title">
	<div class="page-title-heading">
		<div class="page-title-icon">
			<i class="pe-7s-wallet icon-gradient bg-plum-plate"> </i>
		</div>
		<div>Nuevo Cliente</div>
	</div>
</div>


<div class="main-card mb-3 card">
	<div class="card-body">
		<h5 class="card-title">Formulario de Creación de Cliente</h5>
		<form class="needs-validation" action="" method="post">{% csrf_token %}
			    {% include '../utils/form_cabecera.html' %}
			<input type="submit" class="btn btn-primary" value="Guardar">
		</form>
	</div>
</div>

{% endblock %}

inicio/templates/gral/cliente_list.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="app-page-title">
	<div class="page-title-heading">
		<div class="page-title-icon">
			<i class="pe-7s-menu icon-gradient bg-ripe-malin"> </i>
		</div>
		<div>Listado de Clientes</div>

	</div>
</div>


{% if object_list %}
<div class="main-card mb-3 card">
	<div class="card-body">
		<h5 class="card-title">Cliente.</h5>
		<table class="table table-hover table-fixed">
			<tr>
				<th>Razon Social</th>
				<th>Nombre Corto</th>
				<th>Cuit</th>
				<th>Ver Detalle</th>
			</tr>
			{% for cliente in object_list %}
			<tr>
				<td>
					<i class="pe-7s-box2 icon-gradient bg-amy-crisp"></i>
					{{cliente.razon_social}}
				</td>
				<td>{{cliente.nombre_corto }}</td>
				<td>{{cliente.cuit}}</td>
				<td><a href="{% url 'gral:ClienteDetail' pk=cliente.id %}">
						<i class="pe-7s-angle-up-circle"> Ver </i>
				</a></td>
			</tr>
			{% endfor %} {% else %}
			<p>No hay registros para mostrar.</p>
			{% endif %}
		</table>
	</div>
</div>
<a href="{% url 'inicio:abm' %}">
	<button
		class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-wallet icon-gradient bg-plum-plate"></i>Ir al ABM
	</button>
</a>
<a href="{% url 'gral:ProductoCreate' %}">
	<button
		class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-magic-wand icon-gradient bg-mixed-hopes"></i>Crear
		Producto
	</button>
</a>

{% endblock %}

inicio/templates/gral/productoList.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="app-page-title">
<div class="page-title-heading">
   <div class="page-title-icon">
                                        <i class="pe-7s-menu icon-gradient bg-ripe-malin">
                                        </i>
                                    </div>
<div>Listado de Producto</div>
                                     
                                    </div>
</div>


    {% if object_list %}
<div class="main-card mb-3 card">
	<div class="card-body">
	<h5 class="card-title">Listado de produtos.</h5>
		<table class="table table-hover table-fixed">
		  <tr>
		    <th>Código</th>
		    <th>Descripción</th>
		    <th>Cliente</th>
		    <th>Ver Detalle</th>
		  </tr>   
		      {% for producto in object_list %}
		   <tr>
		      <td><i class="pe-7s-box2 icon-gradient bg-amy-crisp">
		        </i>
		        {{producto.codigo}}
		      </td>
		      <td>
		        {{producto.descripcion }}
		      </td>
		      <td>
		        {{producto.cliente}}
		      </td>
		      <td>
			      <a href="{% url 'gral:ProductoDetail' pk=producto.id %}">
			      	<i class="pe-7s-angle-up-circle">
			      			Ver
			      	</i>
			      </a>
		      </td>
		    </tr>
		      {% endfor %}
		
		    {% else %}
		      <p>No hay registros para mostrar.</p>
		    {% endif %}      
		</table>
	</div>
</div>
<a href="{% url 'inicio:abm' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-wallet icon-gradient bg-plum-plate"></i>Ir al ABM
</button>
</a>	
<a href="{% url 'gral:ProductoCreate' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-magic-wand icon-gradient bg-mixed-hopes"></i>Crear Producto
</button>
</a>

{% endblock %}

inicio/templates/gral/producto_detail.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="main-card mb-3 card">
	<div class="card-body">
		<h5 class="card-title">Detalle de producto: {{ producto.descripcion }}</h5>
		<table class="table table-hover table-fixed">
		<tr>
			<th>
				Campo
			</th>
			<th>
				Detalle
			</th>
		</tr>
			<tr>
				<td>Código: </td>
				<td><i class="pe-7s-box2 icon-gradient bg-amy-crisp">
		        </i>
		        	{{producto.codigo}}
		      </td>
		      </tr>
		      <tr>
		      <td>Descripción: </td>
		      
		      <td>
		        {{producto.descripcion }}
		      </td>
		      </tr>
		      
		      <tr>
		      <td>Cliente: </td>
		      <td>
		       	
		       
		        {{producto.cliente}}
		        </td>
		      </tr>	
		</table>
	</div>
</div>
<a href="{% url 'gral:ProductoListView' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-angle-left-circle">Volver</i>
</button>
	</a>		 


{% endblock %}

inicio/templates/gral/producto_form.html
{% extends '../base.html' %}
{%  block cuerpo %}

<div class="app-page-title">
	<div class="page-title-heading">
		<div class="page-title-icon">
			<i class="pe-7s-magic-wand icon-gradient bg-mixed-hopes"> </i>
		</div>
		<div>Crear Producto</div>
	</div>
</div>


	{% include "./partials/pProducto_form.html" %}
{% endblock %}

inicio/templates/gral/producto_list.html
{% extends '../base.html' %}

{%  block cuerpo %}
<div class="app-page-title">
    <div class="page-title-heading">
        <div class="page-title-icon">
            <i class="pe-7s-menu icon-gradient bg-ripe-malin"></i>
        </div>
        <div>Listado de Producto</div>
    </div>
    <!-- Inicio Filtros -->
	<hr/>
	<div class="main-card mb-2 card">
		<div class="card-body">
			<h5 class="card-title">Filtros</h5>
			<table class="table table-hover table-fixed">
				<tr>
					<td>
						<label for="filtroCodigo">Código:</label>
						<input type="text" class="form-control" id="filtroCodigo"
							onkeyup="filtros()"
							placeholder="Ingrese un Código..." />
                    </td>
                    <td>
						<label for="filtroDescripcion">Descripción:</label>
						<input type="text" class="form-control" id="filtroDescripcion"
							onkeyup="filtros()"
							placeholder="Ingrese una descripción..." />
				    </td>
				<td>
						<label for="clientes_select">Cliente:</label>
						<select id="clientes_select" class="form-control"
							onchange="filtros()">
					</td>
				</tr>
			</table>
		</div>
	</div>
	<!-- Fin Filtros 	-->


</div>

{% include './partials/pProducto_list.html'%}
 
<a href="{% url 'inicio:abm' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-wallet icon-gradient bg-plum-plate"></i>Ir al ABM
</button>
</a>	
<a href="{% url 'gral:ProductoCreate' %}">    
<button class="mb-2 mr-2 btn-transition btn btn-outline-primary btn-block">
		<i class="pe-7s-magic-wand icon-gradient bg-mixed-hopes"></i>Crear Producto
</button>
</a>
{% include "./js/producto_list.js" %}
{% endblock %}