informes/urls.py
from django.urls import path
from .views import (main_informes,
                    pendiente_x_cronograma, 
                    obtener_productos)

urlpatterns = [
    path('', main_informes, name='main_informes'),
    path('cronograma/', pendiente_x_cronograma, name='pendiente_x_cronograma'),
    path('cronograma/<int:id_cronograma>/', obtener_productos, name='obtener_productos'),
    ]

inicio/urls.py
from .views import inicio, abm
from django.urls import path, include

urlpatterns = [
                path('', inicio, name='inicio'),
                path('abm/', abm, name='abm'),
]

vd/urls.py
from django.contrib import admin
#from django.contrib.auth import urls
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include(('inicio.urls', 'inicio'), namespace='inicio')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('gral/', include(('gral.urls', 'gral'), namespace='gral')),
    path('venta/', include(('venta.urls', 'venta'), namespace='venta')),
    path('configuraciones/', include(('configuraciones.urls', 'configuraciones'), namespace='configuraciones')),
    path('upoc/', include(('upoc.urls', 'upoc'), namespace='upoc')),
    path('admin/', admin.site.urls, name='admin'),
    path('informes/', include(('informes.urls', 'informes'), namespace='informes')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

informes/models.py
from django.db import models

# Create your models here.

inicio/models.py
from django.db import models

# Create your models here.

informes/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from gral.models import Cliente
from venta.models import Cronograma, Movimientos
@login_required
def main_informes(request):
    context = {'Pendiente x Cronograma' :  ['Muestras los pendientes según el cronograma.', reverse_lazy('informes:pendiente_x_cronograma')],
               'Campaña cerrada' : ['A partir de una campaña se muestras los datos de entregas', '#'],
	        'Devoluciones' : ['Estadisticas de las devoluciones que se han realizado' , '#'],
		'Pedidos Futuros' : ['Esto es un lalalalala para probar la maquetación', '#']
               }
    return render(request, 'informes/index.html', {'context' : context})

def pendiente_x_cronograma(request):
    context = {}
    clientes = Cliente.objects.all()
    context['cliente'] = clientes
    tmp_dict  = {}
    for cliente in clientes:
        cronograma = Cronograma.objects.filter(cliente=cliente.id)
        tmp_dict[cliente.id] = cronograma
    context['cronograma'] = tmp_dict
    return render(request, 'informes/pendiente_x_cronograma.html', {'context' : context })

def obtener_productos(request, id_cronograma):
    productos = Movimientos.objects.pendientes_cronograma(id_cronograma)
    cronograma  = Cronograma.objects.filter(pk=id_cronograma)
    cronograma = cronograma.values()[0]
    return render(request, 'informes/obtener_productos.html', {'productos' : productos, 'cronograma' : cronograma})

inicio/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

@login_required
def inicio(request):
	return render(request, 'index.html', {})

@login_required
def abm(request):
	'''abm
	Aquí se define el contexto que se pasara a la pagina para que muestre los botones como correspondan.
	
	'''
	context = {'Producto' : {'Crear Producto' : {'descripcion' : 'Permite generar productos nuevos.',
												 'url' : reverse_lazy('gral:ProductoCreate'),
												 },
							 'Listar Productos' : {'descripcion' : 'Lista de todos los productos.',
												 'url' : reverse_lazy('gral:ProductoListView'),
												 },
							},
				'Cliente' : {'Crear Cliente' : {'descripcion' : 'Permite dar de alta clientes.',
												'url' : reverse_lazy('gral:ClienteCreate')},
							},
				'Condiciones de Pago' : {'Crear Tipo de Valores' : {'descripcion': 'Crear tipo de valores: Cheques, Efectivo, etc.',
											'url' : reverse_lazy('gral:ClienteCreate')},
										 'Crear Condiciones de Pago' : {'descripcion' : 'Creación de condiciones de pago.',
										    'url' : reverse_lazy('gral:ClienteCreate')},
							},
				}
	return render(request, 'inicio/abm.html', {'context' : context})

inicio/templates/informes/index.html
{% extends '../base.html' %}
{% block cuerpo %}
<div class="row">
  {% for title, values in context.items %}
<div class="col-sm-6">  
  <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ title }}</h5>
        <p class="card-text">{{ values.0 }}</p>
        <a href="{{ values.1 }}" class="btn btn-primary">Generar</a>
      </div>
    </div>
  </div>	
  {% endfor %}
</div>
  {% endblock %}

inicio/templates/informes/obtener_productos.html
{% extends '../base.html' %}
{% block cuerpo %}
<!-- inicio cabecera-->
<div class="app-page-title">
    <div class="page-title-heading">
        <div class="page-title-icon">
            <i class="pe-7s-menu icon-gradient bg-ripe-malin"></i>
        </div>
    <div>Detalle de Pendientes por Cronograma</div>
</div>
<!-- fin cabecera -->

   <!--  -->
   <hr/>
   <div class="main-card mb-2 card">
    <table>
    <tr>
        <ht class="text-center"><h3>Encabezado Cronograma</h3></ht>
    </tr>
        <tr>
    <td id='cronograma-id'><span class="text-primary">Id:</span> {{ cronograma.id }}</td>
    <td id='cronograma-nombre'><span class="text-primary">Nombre:</span> {{ cronograma.nombre }}</td>
    <td id='cronograma-nombre'><span class="text-primary">Fecha Inicio:</span> {{ cronograma.fecha_inicio }}</td>
    <td id='cronograma-nombre'><span class="text-primary">Fecha Finalización:</span> {{ cronograma.fecha_finalizacion }}</td>
    <td id='cronograma-nombre'><span class="text-primary">Terminada:</span>{{ cronograma.terminada }}</td>
        </tr>
    </table>
    </div>
    <hr/>
   <!--  -->



    {% include './partials/pObtener_productos.html'%}




{% endblock %}

inicio/templates/informes/pendiente_x_cronograma.html
{% extends '../base.html' %}
{% block cuerpo %}
<!-- inicio cabecera-->
<div class="app-page-title">
    <div class="page-title-heading">
        <div class="page-title-icon">
            <i class="pe-7s-menu icon-gradient bg-ripe-malin"></i>
        </div>
        <div>Pendientes por Cronograma</div>
    </div>
   

   <!-- filtro -->
   <hr/>
	<div class="main-card mb-2 card">
	<label for="clientes">Cliente</label>
   	<select id='clientes' class='form-class'>
		{% for cliente in context.cliente %}
			<option value='{{ cliente.id }}'>{{ cliente.nombre_corto }}</option>
		{% endfor %}
	</select>
	<input type="button" class="btn btn-primary" value="Filtrar" onclick="filtros()"/>
	</div>
	<!-- fin filtro-->


</div>
<!-- fin cabecera -->
<div class="main-card mb-3 card">
	<div class="card-body">
	<h5 class="card-title">Listado de produtos.</h5>
		<table class="table table-hover table-fixed" id="tablaResultado">
			<tr>
				<th>Id Cliente</th>
				<th>Cronograma</th>
				<th>Ver</th>
			</tr>

			{% for oc in context.cronograma.items %}
				{% for item in oc.1 %}
					<tr>
						<td>{{ oc.0 }}</td>
						<td>{{ item }}</td>
						<td><a href="{% url 'informes:obtener_productos' id_cronograma=item.id %}">Ver</a></td>
					</tr>
				{% endfor %}
			{% endfor %}	

		</table>
	</div>
</div>	

{% include "./js/pendiente_x_cronograma.js" %}
{% endblock %}